# Workflow Code: AngryGoose_v1    DO NOT REMOVE

name: Increment Version on Merge
on:
  pull_request:
    types: [closed]

jobs:
  increment-version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    runs-on: ubuntu-latest # Force this to run on github-hosted runner by using a tag that does not exist on self-hosted runners

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # See https://github.com/im-open/git-version for more details around how to increment major/minor/patch through commit messages
      - uses: im-open/git-version-lite@v1.0.0
        with:
          tag-prefix: 'v' #TODO:  Verify the prefix for your repository tags.  GitHub's recommended prefix is 'v'.  If there is no prefix, delete this arugment.
